#!/bin/sh /etc/rc.common

# copyright            : (C) by 2021 Lin kai 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as         
# published by the Free Software Foundation                                
# You may obtain a copy of the License at                                   
# https://opensource.org/licenses/gpl-2.0.php 


#this script will run by /etc/init.d/rcS after all rc script.
START=99

start() {
	nvram set flag_ota_reboot=0
	nvram set flag_boot_success=1
	nvram set flag_try_sys1_failed=0
	nvram set flag_try_sys2_failed=0

	local system_current=$(nvram get flag_boot_rootfs)
	if [ $system_current -ge 0 -a $system_current -le 1 ]; then
		nvram set flag_last_success=$system_current
	fi
	nvram commit

    #All off by default
    echo 1 > /sys/class/leds/led_blue/brightness
    echo 0 > /sys/class/leds/led_yellow/brightness
    echo 1 > /sys/class/leds/net_blue/brightness
    echo 0 > /sys/class/leds/net_yellow/brightness

    echo "Booting up finished."
}

stop() {
	echo "stop"
}
